name: Actionlint

on:
  pull_request:
    paths:
      - ".github/workflows/**"
  push:
    branches: main
    paths:
      - ".github/workflows/**"
  workflow_dispatch:

# Restrict permissions for GITHUB_TOKEN to minimum required
permissions:
  contents: read
  # All other permissions are implicitly none

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          # Discard `GITHUB_TOKEN` after this step, as we don't need it
          persist-credentials: false
      - uses: cachix/install-nix-action@4e002c8ec80594ecd40e759629461e26c8abed15 # v31.9.0
      - name: Check workflow files
        run: |
          NIXPKGS=$(nix-instantiate --eval -A pkgs.path)
          nix-shell -I nixpkgs="$NIXPKGS" -p actionlint --run actionlint
