name: Builds
on:
  pull_request:
  push:
    branches: main
  # allow "manual" triggering from automatic PRs
  workflow_dispatch:
jobs:
  # Only put untrusted jobs here.
  development:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: cachix/install-nix-action@4e002c8ec80594ecd40e759629461e26c8abed15 # v31.9.0
      - run: nix-build -A git-hooks
      - run: nix-build -A tests
      - run: |
          nix-build -A ci
          result/bin/deploy build
