name: Deployments
on:
  # Run the deployment only once staging has been prepared.
  workflow_run:
    workflows: ["Dry activations"]
    branches: [main]
    types:
      - completed
  push:
    branches: [main, production]
jobs:
  deploy-environment:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - environment: staging
            host: tracker-staging.security.nixos.org
            branch: main
          - environment: production
            host: tracker.security.nixos.org
            branch: production
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: cachix/install-nix-action@4e002c8ec80594ecd40e759629461e26c8abed15 # v31.9.0
      - uses: webfactory/ssh-agent@a6f90b1f127823b31d4d4a8d96047790581349bd # v0.9.1
        with:
          ssh-private-key: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
      - name: Trust staging server public SSH host keys
        run: cat ./infra/host_keys >> ~/.ssh/known_hosts
      - name: Deploy to ${{ matrix.environment }}
        # Only deploy production when on production branch
        if: github.ref_name == matrix.branch
        run: nix-shell default.nix -A ci --run "deploy switch ${{ matrix.host }}"
